### ISSUE TITLE
What you can do for Ethereum 2.0 a.k.a. sharding?

### ISSUE THREAD

**Issue by hwwhww** [EtherTW/talks#20]
> Please specify a **title** for your talk. / 請為講題下個標題
### Language / 語言
- [x] English
- [ ] 中文
- [ ] 其他：

### Abstract / 大綱 (Optional)
*Sharding* is the Ethereum core protocol scaling solution that will distribute the computation and storage overhead to multiple "shard chains" with the security guarantee. In this way, we can optimize the computational resources and gain much higher TPS.

Sharding also enables us to have a new chance to redesign and optimize the Ethereum blockchain - *Etheruem 2.0* - many fascinating ideas can be applied in shard chains without backward compatibility problem.

A lazy Ethereum Foundation researcher will give a brief intro to the sharding research and implementation. Also, how can **you** contribute to the cutting-edge R&D. 🦄️

### References / 參考資料 (Optional)
> Usually this section is updated when the talk is delivered. 講題講完之後再更新即可

Not very relevant to this talk but you may be interested in:
* [Ethereum Sharding Research Compendium](https://tinyurl.com/sharding-compendium)
* [Announcing Beneficiaries of the Ethereum Foundation Grants - Ethereum Blog](https://blog.ethereum.org/2018/03/07/announcing-beneficiaries-ethereum-foundation-grants/)
* [Announcing May 2018 Cohort of EF Grants - Ethereum Blog](https://blog.ethereum.org/2018/05/02/announcing-may-2018-cohort-ef-grants/)

### Preferences / 偏好

- [ ] Accept Livestream / 可直播
- [x] No livestream, accept video recording / 不直播，但可錄影
- [ ] Prohibit video recording / 不可直播也不可錄影
- [x] Prohibit photographing / 禁止現場拍照

#### Time / 演講時間 (Optional)
20-30 mins

#### Contact info / 聯繫方式
gitter: [hwwhww](https://gitter.im/hwwhww)

#### Other Preferences / 其他偏好請補充 (Optional)
Ice Bear hates tomatoes.

**Comment by thogiti** [comment]
Can you share your slides from the talk Hsiao-Wei?

**Comment by willliw** [comment]
@thogiti  https://docs.google.com/presentation/d/1G5UZdEL71XAkU5B2v-TC3lmGaRIu2P6QSeF8m3wg6MU/edit#slide=id.p4
