### ISSUE TITLE
A quick walkthrough of cryptokitties smart contract code

### ISSUE THREAD

**Issue by pieceofr** [EtherTW/talks#7]
> Please specify a **title** for your talk. / 請為講題下個標題
A quick walkthrough of cryptokitties smart contract code
### Language / 語言

- [ ] English
- [x] 中文
- [ ] 其他：

### Abstract / 大綱 (Optional)
 -  what is cryptokitties
 - Quick walkthrough cryptokitties smart contract code 

### References / 參考資料 (Optional)

> Usually this section is updated when the talk is delivered. 講題講完之後再更新即可

- [slides / 投影片](https://hackmd.io/p/Bk8uIhYVz#/)

### Preferences / 偏好

- [x] Accept Livestream / 可直播
- [ ] No livestream, accept video recording / 不直播，但可錄影
- [ ] Prohibit video recording / 不可直播也不可錄影
- [ ] Prohibit photographing / 禁止現場拍照

#### Time / 演講時間 (Optional)
 30 min
> The talk is usually 30 min with extra 10 min Q&A, specify here if longer or shorter is preferred. 一般演講時間為 30 分鐘與 10 min 問答時間，可註明想要更長或更短。

#### Contact info / 聯繫方式
pieceofr@gmail.com or facebook: Rachael Pai
> Specified a way that co-organizers can contact you. 留下一個共同組織者能聯絡您的方式。

#### Other Preferences / 其他偏好請補充 (Optional)

------

**Comment by changtimwu** [comment]
結果還是有人把 `mixGenes` 從 EVM bytecode 還原回 source
https://medium.com/@sean.soria/cryptokitties-mixgenes-function-69207883fc80

**Comment by changtimwu** [comment]
無論ERC多少,  token 本來就一律都是 indivisble,  一般 contract 內的 token 計量變數(ex totalSupply, balance contract) 型別都是 uint256,  平常會在 wallet 上看到小數點是因為 decimals這個變數告知這個 token習慣使用的大單位,  技術上來說想要 indivisble 就是把 contract內的 decimals設為 0 就好.

**Comment by juincc0** [comment]
請問有投影片嗎

**Comment by pieceofr** [comment]
@changtimwu  謝謝指教! 想請問 decimals 的問題。的確 token 回傳 uint256 所以是不可以分割的。但現實中我的 token 是有看到 decimal 後面的數字，你是說是因為要告知使用者這個 token 使用的是大單位。這個意思是說，最上層也就是與使用者接觸的那層所使用的 token 跟 small contract 裡 token supply  裡的 token 單位是不一樣的嗎? 也就說比如使用者看到 2.56 (100token)那麼底層是 256 token, 所以使用者看到的 token 的單位是 (100token ) 是這樣嗎?
