### ISSUE TITLE
Simple Smart Contract Control System: a system perspective on operating Ethereum smart contracts (basic tutorial)

### ISSUE THREAD

**Issue by yslin1013** [EtherTW/talks#9]
### Title / 標題
Simple Smart Contract Control System (basic tutorial)
 -- a system perspective on operating Ethereum smart contracts 

### Language / 語言
- [ ] English
- [x] 中文
- [ ] 其他：

### Abstract / 大綱
此為初學者導向技術開發主題 (basic tutorial)。講者以系統的角度出發，說明如何基於SSCCS系統設計，使得初學者較容易進入狀況、便於開發以太坊智能合約之相關應用。主題過程中亦針對相關周邊技術，進行初步簡單的講解。

### References / 參考資料
- [slides / 投影片](https://goo.gl/zuhvSZ)

### Preferences / 偏好
- [x] Accept Livestream / 可直播
- [ ] No livestream, accept video recording / 不直播，但可錄影
- [ ] Prohibit video recording / 不可直播也不可錄影
- [ ] Prohibit photographing / 禁止現場拍照

#### Time / 演講時間
30 min

#### Contact info / 聯繫方式
yishanl@cs.nctu.edu.tw
https://www.linkedin.com/in/yishanl/

#### Other Preferences / 其他偏好請補充
None

**Comment by juincc0** [comment]
請問有投影片嗎

**Comment by yslin1013** [comment]
當日PPT可參考上方連結，謝謝。
